services:
  - type: web
    name: mahjong-server
    env: python
    buildCommand: ""
    sstartCommand: uvicorn server:app --host 0.0.0.0 --port 10000 --proxy-headers
    plan: free
    envVars:
      - key: PORT
        value: 10000